name: Java CI
on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle','**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-test-
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build Native Binary
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          ./gradlew devSnapshot --info --stacktrace --no-daemon
