name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#            ~/.m2/repository
#          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-test-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 23.0.1
          distribution: graalvm
          cache: gradle
#      - name: Docker login
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build And Push Docker Image
        env:
#          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
#          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          #export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_REPOSITORY_PATH}/image-organizer" | sed -e 's#//#/#' -e 's#^/##'`
          #./gradlew check dockerPush --no-daemon
          ./gradlew build --no-daemon
