name: Java CI
on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches:
      - main
jobs:
  build:
    name: devSnapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'      # See 'Options' for more details
          distribution: 'graalvm-community' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: gradle
      - name: Build Native Binary
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          ./gradlew devSnapshot --stacktrace --no-daemon
